name: Spotify Recently Played Workflow

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-readme-with-spotify:
    name: Update Spotify Recently Played
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Recently Played
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "SPOTIFY_RECENTLY_PLAYED"
          feed_list: "https://spotify-recently-played-readme.vercel.app/api?user=31hpn5tt5qovlmi2ehq5wtnodebe"
          max_post_count: 5
          template: "🎵 $title - $artist"
          commit_message: "Updated Spotify recently played"
